version: 2

orbs:
  node: circleci/node@4.1

jobs:
  build-deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - name: install modules
        run: npm install 
      - name: build source
        run: npm run build
      - name: export
        run: npm run export

workflows:
  version: 2
  on-master-update: 
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - master
