version: 2

orbs:
  node: circleci/node@4.1

jobs:
  build-deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: npm install && npm run build && npm run export
      - run:
          name: deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs

workflows:
  version: 2
  on-master-update: 
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - master
