version: 2

orbs:
  node: circleci/node@4.1

jobs:
  build-deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: npm install && npm run build && npm run export

workflows:
  version: 2
  on-master-update: 
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - master
