version: 1.0.0

orbs:
  node: circleci/node@4.1

jobs:
  build-deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install Node dependencies
          command: npm install
       - run:
          name: Deploy
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "<>"
            npm run export

workflows:
  sample: 
    jobs:
      - build-deploy
        filters:
          branches:
            only:
              - master
